version: "3.8"

services:
  backend:
    build: ./anote-api
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./anote-api:/app
    env_file:
      - ./anote-api/.env
    depends_on:
      - database

  frontend:
    build: ./anote-ui
    container_name: angular_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: julitaw
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: anote
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
